services:
  api:
    build:
      context: .
      dockerfile: MoneybaseChat.api/Dockerfile
    ports:
      - "5666:5666"
    depends_on:
      mariadb:
          condition: service_healthy
      rabbitmq:
          condition: service_healthy
    networks:
      moneybase:
        ipv4_address: 172.20.0.10

  mariadb:
    image: mariadb:10
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: moneybase_chat
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1","-u", "admin", "-p1234"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      moneybase:
        ipv4_address: 172.20.0.11

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5673:5672"   # Main protocol
      - "15673:15672" # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_port_connectivity"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      moneybase:
        ipv4_address: 172.20.0.12

networks:
  moneybase:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
