// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneybaseChat.infrastructure.persistence;

#nullable disable

namespace MoneybaseChat.infrastructure.Migrations
{
    [DbContext(typeof(MoneybaseChatContext))]
    [Migration("20250721062410_AddedTeamIdentifier")]
    partial class AddedTeamIdentifier
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MoneybaseChat.domain.entities.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("Seniority")
                        .HasColumnType("int")
                        .HasColumnName("seniority");

                    b.Property<int>("Team")
                        .HasColumnType("int")
                        .HasColumnName("team");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("Team");

                    b.ToTable("agent", (string)null);
                });

            modelBuilder.Entity("MoneybaseChat.domain.entities.ChatRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Agent")
                        .HasColumnType("int")
                        .HasColumnName("agent");

                    b.Property<Guid>("Identifier")
                        .HasColumnType("char(36)")
                        .HasColumnName("identifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastPulse")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_pulse");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("Agent");

                    b.HasIndex(new[] { "Identifier" }, "unique_chat_request_identifier")
                        .IsUnique();

                    b.ToTable("chat_request", (string)null);
                });

            modelBuilder.Entity("MoneybaseChat.domain.entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("Identifier")
                        .HasColumnType("char(36)")
                        .HasColumnName("identifier");

                    b.Property<bool>("IsOverflowTeam")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_overflow_team");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("ShiftDurationInMinutes")
                        .HasColumnType("int")
                        .HasColumnName("shift_duration_minutes");

                    b.Property<TimeSpan>("ShiftStartTime")
                        .HasColumnType("TIME")
                        .HasColumnName("shift_start_time");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("team", (string)null);
                });

            modelBuilder.Entity("MoneybaseChat.domain.entities.Agent", b =>
                {
                    b.HasOne("MoneybaseChat.domain.entities.Team", "TeamNavigation")
                        .WithMany("Agents")
                        .HasForeignKey("Team")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamNavigation");
                });

            modelBuilder.Entity("MoneybaseChat.domain.entities.ChatRequest", b =>
                {
                    b.HasOne("MoneybaseChat.domain.entities.Agent", "AgentNavigation")
                        .WithMany("ChatRequests")
                        .HasForeignKey("Agent");

                    b.Navigation("AgentNavigation");
                });

            modelBuilder.Entity("MoneybaseChat.domain.entities.Agent", b =>
                {
                    b.Navigation("ChatRequests");
                });

            modelBuilder.Entity("MoneybaseChat.domain.entities.Team", b =>
                {
                    b.Navigation("Agents");
                });
#pragma warning restore 612, 618
        }
    }
}
